export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POST = 'FETCH_POST';
export const BREADCRUMB = 'BREADCRUMB';
export const SEARCH_POSTS = 'SEARCH_POSTS';
export const INCREMENT_PAGENUM = 'INCREMENT_PAGENUM';
export const DECREMENT_PAGENUM = 'DECREMENT_PAGENUM'